[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false
seeds=true

[programs.localnet]
counter = "Dt1Jy254GZUAUFCUcUSmSuAG3Enx1EJHvBEhRowaDQGH"
[programs.devnet]
counter = "Dt1Jy254GZUAUFCUcUSmSuAG3Enx1EJHvBEhRowaDQGH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/counter"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
